version: '3.1'

services:     
  app:
    build: .
    container_name: crud-api
    depends_on:
      - db                
    ports: 
        - 3000:3000          
    environment:
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - DB_DATABASE=sistema
      - DB_PORT=3306
      - WAIT_HOSTS=db:3306
    volumes:
      - .:/src/         
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=sistema
    ports:
      - "3306:3306"
    volumes:
      - ./src/database:/app/api
  adminer:
    image: adminer
    ports:
      - 8080:8080